version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5435:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "python main.py migration && python main.py process cnap_reports"

volumes:
  db_data:
